ALTER TABLE alumni_quiz_results ADD COLUMN IF NOT EXISTS user_id INTEGER;
ALTER TABLE alumni_quiz_results ADD COLUMN IF NOT EXISTS quiz_id INTEGER;
ALTER TABLE alumni_quiz_results ADD COLUMN IF NOT EXISTS answers JSONB;
ALTER TABLE alumni_quiz_results ADD COLUMN IF NOT EXISTS score INTEGER;
ALTER TABLE alumni_quiz_results ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT NOW();
ALTER TABLE quizzes ADD COLUMN IF NOT EXISTS alumni_visible BOOLEAN DEFAULT FALSE;
